### ISSUE TITLE
Port configuration not working

### ISSUE THREAD

**Issue by aisthesis** [optbot/restapi#5]
It looks like even when I configure the port as 8080, it is still starting the server on 8081:

```
$ npm start -- --port=8080

> @optbot/restapi@0.0.1 start /mnt/disk1/Workspace/restapi
> node lib/app.js "--port=8080"

Express server started at http://:::8081
```

**Comment by mscappini** [comment]
This should now be fixed.

**Comment by Irialad** [comment]
These should generally be closed by the person who discovered them, no?

**Comment by mscappini** [comment]
It's been six days, plus the approach has changed entirely.

**Comment by Irialad** [comment]
Fair point. We should make decisions on handling of these things, and maybe
meet to discuss and groom/triage at regular points?
